### ISSUE TITLE
0.1 Release Checklist

### ISSUE THREAD

**Issue by lucaspoffo** [lucaspoffo/renet#35]
This is the tracking issue for the `0.1` release of the library:

- [X] Add section in README for Configuration
- [ ] Add section in README for Secure Connection
- [X] Add logging for `renetcode`
- [X] Make sure the library is working in all OS: (fortunately, I have all of them available)
    - [X] Linux
    - [X] MacOS
    - [X] Windows
- [X] Host `chat_demo::matcher` in a remote server and verify how it behaves
- [ ] Review all public API exports
- [ ] Review documentation from public API
- [X] Verify for any missing util methods from `rechannel` and `renetcode`
- [ ] Prepare announcement for reddit/discord
